"use client";

import { useMemo, useRef, useState } from "react";
import { Activity, ArrowDownLeft, ArrowRight, ArrowUpRight, BadgeCheck, Bell, ChevronDown, CircleHelp, Clock3, CloudUpload, ExternalLink, Eye, FileCheck2, FileText, Fingerprint, Globe2, ImagePlus, Leaf, LockKeyhole, MapPin, Menu, MoreHorizontal, Plus, Search, ShieldCheck, SlidersHorizontal, Sparkles, Wallet, X } from "lucide-react";
import { initialAssets, milestones, ProofAsset, rupees } from "@/lib/demo-data";

type View = "Overview" | "Evidence" | "Milestones" | "Impact ledger";
const nav: { name: View; icon: typeof Activity }[] = [{ name: "Overview", icon: Activity }, { name: "Evidence", icon: ImagePlus }, { name: "Milestones", icon: FileCheck2 }, { name: "Impact ledger", icon: Globe2 }];

export default function Dashboard() {
  const [view, setView] = useState<View>("Overview");
  const [assets, setAssets] = useState(initialAssets);
  const [selected, setSelected] = useState<ProofAsset | null>(null);
  const [search, setSearch] = useState("");
  const [toast, setToast] = useState("");
  const [createOpen, setCreateOpen] = useState(false);
  const uploadRef = useRef<HTMLInputElement>(null);
  const visibleAssets = useMemo(() => assets.filter(a => `${a.title} ${a.site} ${a.status}`.toLowerCase().includes(search.toLowerCase())), [assets, search]);

  function flash(message: string) { setToast(message); window.setTimeout(() => setToast(""), 3000); }
  function uploadFiles(files: FileList | null) {
    if (!files?.length) return;
    const next = Array.from(files).map((file, i): ProofAsset => ({ id: `PP-${Math.random().toString(16).slice(2, 8).toUpperCase()}`, title: file.name.replace(/\.[^.]+$/, "").replace(/[-_]/g, " "), site: "Vatadra check dam", date: "Just now", trust: .58, status: "New", image: URL.createObjectURL(file), coordinates: "Location pending", hash: "Hashing original…", note: "Your original has been received. ProofPay is extracting metadata and preparing authenticity checks.", checks: [{ label: "Milestone relevance", value: 0, detail: "Analysis queued" }, { label: "Location match", value: 0, detail: "Awaiting GPS metadata" }, { label: "Capture time", value: 0, detail: "Reading EXIF" }, { label: "Originality", value: 0, detail: "Computing perceptual hash" }] }));
    setAssets(prev => [...next, ...prev]); setView("Evidence"); flash(`${files.length} original${files.length > 1 ? "s" : ""} added to the evidence queue`);
  }

  return <main className="shell">
    <aside className="sidebar">
      <div className="brand"><div className="brand-mark"><span /></div><span>proofpay</span><span className="brand-beta">FIELD NOTES</span></div>
      <div className="org-switch"><div className="org-avatar">V</div><div className="org-copy"><b>Vatadra Watershed</b><small>Impact workspace</small></div><ChevronDown size={15}/></div>
      <div className="nav-label">WORKSPACE</div>
      <nav>{nav.map(item => { const Icon = item.icon; return <button key={item.name} onClick={() => setView(item.name)} className={`nav-link ${view === item.name ? "active" : ""}`}><Icon size={17}/><span>{item.name}</span>{item.name === "Evidence" && <i>3</i>}</button>; })}</nav>
      <div className="nav-label projects-label">YOUR PROJECTS <button aria-label="Create project" onClick={() => setCreateOpen(true)}><Plus size={15}/></button></div>
      <button className="project-link selected-project"><span className="project-dot"/>Vatadra Check Dam</button>
      <button className="project-link"><span className="project-dot sage"/>Anand Green Belt</button>
      <button className="project-link"><span className="project-dot ochre"/>Lake Reborn · Nadiad</button>
      <div className="side-bottom"><div className="help-card"><div className="help-icon"><CircleHelp size={16}/></div><div><b>Need a hand?</b><span>Visit the field guide</span></div><ArrowRight size={14}/></div><div className="profile-row"><div className="profile-avatar">AM</div><div><b>Ananya Mehta</b><span>Funder · CSR team</span></div><MoreHorizontal size={18}/></div></div>
    </aside>

    <section className="main-area">
      <header className="topbar"><div className="crumb"><span>Projects</span><span>/</span><b>Vatadra Check Dam</b><span className="live-dot"/> <span className="live-label">LIVE DEMO</span></div><div className="top-actions"><div className="simulation-pill"><span/>SIMULATION MODE</div><button className="icon-button" aria-label="Notifications" onClick={() => flash("You’re all caught up")}><Bell size={17}/><i/></button><div className="top-divider"/><button className="avatar-mini">AM</button></div></header>

      <div className="content-wrap">
        <div className="page-heading"><div><div className="eyebrow">GUJARAT · ANAND DISTRICT <span>↗</span></div><h1>{view === "Overview" ? "Vatadra Check Dam" : view}</h1><p>{view === "Overview" ? "A stronger watershed, built one verified milestone at a time." : view === "Evidence" ? "Every field submission, with its provenance intact." : view === "Milestones" ? "Funding follows the proof. Each release is explained." : "Open records. Original evidence. A public chain of trust."}</p></div><div className="heading-actions"><button className="button button-quiet" onClick={() => setView("Impact ledger")}><Eye size={15}/> View public ledger <ExternalLink size={13}/></button><button className="button button-dark" onClick={() => uploadRef.current?.click()}><CloudUpload size={16}/> Add evidence</button><input ref={uploadRef} type="file" accept="image/*,video/*" multiple hidden onChange={e => uploadFiles(e.target.files)}/></div></div>

        <div className="project-strip"><div className="strip-item"><span className="strip-icon"><MapPin size={15}/></span><div><small>PROJECT SITE</small><b>Vatadra village <span>·</span> 22.394° N, 72.858° E</b></div></div><div className="strip-item"><span className="strip-icon green"><Leaf size={15}/></span><div><small>IMPLEMENTING PARTNER</small><b>Jal Jeevan Collective</b></div></div><div className="strip-item"><span className="strip-icon gold"><Wallet size={15}/></span><div><small>FUNDED BY</small><b>Aranya Foundation</b></div></div><div className="strip-date">PROJECT SINCE <b>04 AUG 2026</b></div></div>

        {view === "Overview" && <>
          <div className="stats-grid"><Stat label="COMMITTED FUNDS" value="₹27.5L" note="of ₹32 lakh project budget" kind="money"/><Stat label="VERIFIED & RELEASED" value="₹8.5L" note="1 milestone · 18 pieces of proof" kind="released"/><Stat label="EVIDENCE RECEIVED" value="53" note="Across 3 active milestones" kind="evidence"/><Stat label="PROJECT TRUST" value="87.4" suffix="/100" note="↑ 4.2 points this month" kind="trust"/></div>
          <div className="overview-grid"><section className="panel milestones-panel"><div className="panel-heading"><div><div className="section-kicker">PAYMENT PROGRESS</div><h2>Milestones</h2></div><button className="text-button" onClick={() => setView("Milestones")}>All milestones <ArrowRight size={14}/></button></div><div className="milestone-list">{milestones.map((m,i)=><div className="milestone-row" key={m.id}><div className={`mile-icon ${m.state === "Released" ? "done" : m.state === "In verification" ? "verifying" : "collecting"}`}>{m.state === "Released" ? <BadgeCheck size={17}/> : m.state === "In verification" ? <Activity size={17}/> : <Clock3 size={16}/>}</div><div className="mile-main"><div className="mile-meta"><span>{m.id}</span><span className={`status ${m.state === "Released" ? "status-done" : m.state === "In verification" ? "status-review" : "status-wait"}`}>{m.state}</span></div><h3>{m.name}</h3><div className="progress-line"><span style={{width:`${m.progress}%`}} className={i === 0 ? "complete" : ""}/></div><div className="mile-foot"><span>{m.progress}% evidenced <i>·</i> {m.assets} assets</span><span>Due {m.date}</span></div></div><div className="mile-amount">{rupees(m.amount)}<small>{i===0 ? "RELEASED" : "HELD IN SIMULATION"}</small></div></div>)}</div><div className="release-note"><span><LockKeyhole size={15}/></span><p>Funds release when the evidence clears <b>80% trust.</b><br/><small>Every decision is recorded on the public ledger.</small></p><button onClick={() => flash("Release policy: 80% trust threshold · 48 hour dispute window")}>How it works <ArrowRight size={13}/></button></div></section>
          <section className="panel site-panel"><div className="panel-heading"><div><div className="section-kicker">FIELD OVERVIEW</div><h2>One site, getting stronger</h2></div><button className="round-more" aria-label="More options" onClick={() => flash("Site overview for Vatadra village")}><MoreHorizontal size={18}/></button></div><div className="site-map"><div className="map-wash"/><div className="contour contour-a"/><div className="contour contour-b"/><div className="map-river"/><div className="map-road"/><span className="map-label label-vatadra">VATADRA</span><span className="map-label label-dam">CHECK DAM</span><span className="map-label label-field">NORTH PLOT</span><div className="map-pin pin-main"><MapPin size={17}/><span>53 proofs</span></div><div className="map-pin pin-north"><span/></div><div className="map-legend"><span><i className="legend-verified"/>Verified site</span><span><i className="legend-pending"/>Collecting evidence</span></div><div className="map-scale">0 <span/> 250 m</div></div><div className="site-stats"><div><strong>3</strong><span>active sites</span></div><div><strong>1.8 ha</strong><span>work footprint</span></div><div><strong>22.4°</strong><span>north latitude</span></div></div></section></div>
          <div className="section-row"><div><div className="section-kicker">FRESH FROM THE FIELD</div><h2>Evidence stream <span>· {assets.length} recent</span></h2></div><button className="button button-quiet" onClick={() => setView("Evidence")}>Browse all evidence <ArrowRight size={14}/></button></div>
          <EvidenceGrid assets={assets.slice(0,3)} onSelect={setSelected}/>
        </>}
        {view === "Evidence" && <><div className="toolbar"><div className="searchbox"><Search size={16}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search evidence, sites, or claims…"/></div><button className="filter-button" onClick={()=>flash("Showing all statuses and project sites")}><SlidersHorizontal size={15}/> Filters <span>2</span></button><div className="result-count">{visibleAssets.length} PROOFS</div></div><EvidenceGrid assets={visibleAssets} onSelect={setSelected}/><div className="upload-drop" onClick={()=>uploadRef.current?.click()}><div className="upload-symbol"><CloudUpload size={19}/></div><b>Bring the field into focus</b><span>Drop images or video here, or <u>browse files</u>. Originals are never altered.</span></div></>}
        {view === "Milestones" && <><div className="mile-summary"><div><span>PROJECT BUDGET</span><b>₹32,00,000</b></div><div><span>FUNDED TO DATE</span><b>₹27,50,000</b></div><div><span>RELEASED</span><b>₹8,50,000</b></div><div><span>AWAITING VERIFICATION</span><b>₹12,50,000</b></div><button className="button button-dark" onClick={()=>setCreateOpen(true)}><Plus size={15}/> New milestone</button></div><div className="milestone-cards">{milestones.map((m,i)=><article className="panel milestone-card" key={m.id}><div className="card-top"><span>{m.id}</span><span className={`status ${m.state === "Released" ? "status-done" : m.state === "In verification" ? "status-review" : "status-wait"}`}>{m.state}</span></div><h2>{m.name}</h2><p>Visual evidence reviewed against the agreed site criteria and capture window.</p><div className="card-amount">{rupees(m.amount)}<small>milestone allocation</small></div><div className="card-progress"><div><span>Evidence collected</span><b>{m.progress}%</b></div><div className="progress-line"><span className={i===0?"complete":""} style={{width:`${m.progress}%`}}/></div></div><div className="card-bottom"><span><ShieldCheck size={14}/> Trust score <b>{m.trust}%</b></span><span>{m.assets} linked assets</span></div>{i===1&&<button className="release-action" onClick={()=>flash("Release remains simulated until the milestone verdict is VERIFIED.")}>Review verification <ArrowRight size={14}/></button>}</article>)}</div></>}
        {view === "Impact ledger" && <><div className="ledger-banner"><div className="ledger-emblem"><Fingerprint size={29}/></div><div><span>PUBLIC RECORD · VERIFIED BY EVIDENCE</span><h2>Every rupee leaves a trail.</h2><p>Explore claims from Vatadra Check Dam and follow each one to its original, time-stamped field evidence.</p></div><div className="ledger-banner-count"><b>18</b><span>VERIFIED CLAIMS</span></div></div><div className="ledger-filters"><b>Impact claims</b><span>Showing 3 of 18</span><div className="ledger-chip"><i/> Independently verifiable</div></div><div className="claim-list">{[{title:"Foundation laid across the eastern channel",tag:"SITE FOUNDATION",metric:"42 m",text:"Continuous stone foundation prepared across the eastern channel bed.",img:assets[0]},{title:"Native saplings established",tag:"SITE RESTORATION",metric:"312",text:"Native saplings planted across the northern restoration plot.",img:assets[1]},{title:"Stone pitching completed on east embankment",tag:"CHECK DAM",metric:"68%",text:"East bank reinforced with hand-placed stone pitching.",img:assets[2]}].map((c,i)=><button className="claim-row" key={c.title} onClick={()=>setSelected(c.img)}><img src={c.img.image} alt=""/><div className="claim-main"><span>{c.tag} <i/> VERIFIED CLAIM · {String(i+1).padStart(2,"0")}</span><h3>{c.title}</h3><p>{c.text}</p><small><LockKeyhole size={12}/> Source hash · {c.img.hash}</small></div><div className="claim-metric"><b>{c.metric}</b><span>{i===1?"SAPLINGS":"OF WORK VERIFIED"}</span><ArrowRight size={16}/></div></button>)}</div></>}
      </div>
    </section>
    {selected && <EvidenceModal asset={selected} onClose={()=>setSelected(null)} onVerify={()=>{setAssets(prev=>prev.map(a=>a.id===selected.id?{...a,status:"Verified",trust:.91}:a));setSelected(null);flash("Evidence verified · verdict added to the audit trail");}}/>}
    {createOpen && <CreateModal onClose={()=>setCreateOpen(false)} onCreate={(name)=>{setCreateOpen(false);flash(`${name} is ready to configure`);}}/>}
    {toast && <div className="toast"><span><BadgeCheck size={16}/></span>{toast}<button aria-label="Dismiss" onClick={()=>setToast("")}><X size={14}/></button></div>}
  </main>;
}

function Stat({label,value,note,kind,suffix}:{label:string;value:string;note:string;kind:string;suffix?:string}){return <article className={`stat-card stat-${kind}`}><div className="stat-head"><span>{label}</span><button aria-label={`${label} information`}><CircleHelp size={14}/></button></div><div className="stat-value">{value}{suffix&&<small>{suffix}</small>}</div><div className="stat-note">{kind==="money"?<Wallet size={13}/>:kind==="released"?<ArrowUpRight size={13}/>:kind==="evidence"?<ImagePlus size={13}/>:<Activity size={13}/>} {note}</div>{kind==="trust"&&<div className="trust-arcs"><i/><i/><i/></div>}</article>}
function EvidenceGrid({assets,onSelect}:{assets:ProofAsset[];onSelect:(a:ProofAsset)=>void}){return <div className="evidence-grid">{assets.map((a,i)=><button className="evidence-card" key={a.id} onClick={()=>onSelect(a)}><div className="evidence-image"><img src={a.image} alt={a.title}/><span className={`proof-status ${a.status.toLowerCase()}`}>{a.status === "Verified"?<BadgeCheck size={12}/>:a.status === "Review"?<Clock3 size={12}/>:<Sparkles size={12}/>} {a.status}</span><span className="image-number">0{i+1} / 53</span><span className="expand-view"><ArrowUpRight size={16}/></span></div><div className="evidence-info"><div className="evidence-location"><MapPin size={12}/>{a.site.toUpperCase()}<span>·</span>{a.date}</div><h3>{a.title}</h3><div className="evidence-bottom"><span className="trust-label"><i className={a.trust>=.8?"good":"mid"}/><b>{Math.round(a.trust*100)}%</b> trust score</span><span className="proof-id">{a.id}</span></div></div></button>)}</div>}
function EvidenceModal({asset,onClose,onVerify}:{asset:ProofAsset;onClose:()=>void;onVerify:()=>void}){return <div className="modal-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)onClose()}}><section className="evidence-modal"><button className="modal-close" onClick={onClose}><X size={18}/></button><div className="modal-photo"><img src={asset.image} alt={asset.title}/><span className="photo-lock"><LockKeyhole size={12}/> ORIGINAL · PRIVATE</span></div><div className="modal-details"><div className="modal-eyebrow">EVIDENCE RECORD <span>·</span> {asset.id}</div><h2>{asset.title}</h2><div className="modal-location"><MapPin size={14}/>{asset.site}<i/> <Clock3 size={13}/>{asset.date}</div><p className="ai-caption">“{asset.note}”</p><div className="trust-score"><div><small>ASSET TRUST SCORE</small><b>{Math.round(asset.trust*100)}<span>/100</span></b></div><div className="score-ring" style={{"--score":`${asset.trust*100}%`} as React.CSSProperties}><span>{asset.trust>=.8?"PASS":"REVIEW"}</span></div></div><div className="check-list">{asset.checks.map(c=><div key={c.label} className="check-row"><span className="check-mark"><BadgeCheck size={14}/></span><div><b>{c.label}</b><small>{c.detail}</small></div><strong>{c.value}%</strong><div className="check-track"><i style={{width:`${c.value}%`}}/></div></div>)}</div><div className="provenance"><div><Fingerprint size={15}/><b>PROVENANCE CHAIN</b><span>Integrity confirmed</span></div><p><span>SHA-256</span><code>{asset.hash}</code><button aria-label="Copy hash" onClick={()=>navigator.clipboard?.writeText(asset.hash)}>Copy</button></p><p><span>CAPTURED AT</span><code>{asset.coordinates}</code></p></div><div className="modal-actions"><button className="button button-quiet" onClick={onClose}>Close record</button>{asset.status!=="Verified"&&<button className="button button-dark" onClick={onVerify}><ShieldCheck size={15}/> Approve in simulation</button>}</div></div></section></div>}
function CreateModal({onClose,onCreate}:{onClose:()=>void;onCreate:(name:string)=>void}){const [name,setName]=useState("");return <div className="modal-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)onClose()}}><section className="create-modal"><button className="modal-close" onClick={onClose}><X size={18}/></button><div className="section-kicker">WORKSPACE SETUP</div><h2>Start with a place.</h2><p>Give your project a name. You can add the budget, partner and proof criteria next.</p><label>PROJECT NAME<input autoFocus value={name} onChange={e=>setName(e.target.value)} placeholder="e.g. Anand Green Belt"/></label><label>PROJECT LOCATION<input placeholder="Village, district"/></label><div className="modal-actions"><button className="button button-quiet" onClick={onClose}>Cancel</button><button className="button button-dark" disabled={!name.trim()} onClick={()=>onCreate(name.trim())}><Plus size={15}/> Create project</button></div></section></div>}
